; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:WijiBoard]
platform = espressif32
board = WijiBoard
upload_protocol = esptool
framework = arduino
board_build.custom_boards_dir = boards
monitor_speed = 115200
lib_deps =
	ayushsharma82/ElegantOTA@^3.1.5
	ESP32Async/AsyncTCP@^3.3.2
	ESP32Async/ESPAsyncWebServer@^3.7.1
	waspinator/AccelStepper@^1.64
	arduino-libraries/Stepper@^1.1.3
	bbx10/DNSServer@^1.1.0

build_flags =
	-DELEGANTOTA_USE_ASYNC_WEBSERVER
